---
  - name: Install packages with chocolatey
    win_chocolatey:
      name: '{{ item }}'
      state: present
    with_items: '{{ win_software_chocolatey_citrix }}'
    register: sw_installed
      
  - name: Install Printers # Very unique to the deviceTRUST environment.
    win_shell: |
      if(get-printerdriver -name "Generic / Text Only"){}else{Add-PrinterDriver -Name "Generic / Text Only"}
      if(get-printer -name "Corporate"){}else{Add-Printer -Name "Corporate" -DriverName "Generic / Text Only" -PortName LPT1:}
      if(get-printer -name "Floor 1"){}else{Add-Printer -Name "Floor 1" -DriverName "Generic / Text Only" -PortName LPT2:}
      if(get-printer -name "Floor 2"){}else{Add-Printer -Name "Floor 2" -DriverName "Generic / Text Only" -PortName LPT3:}
    args:
        creates: '{{ directory_logging }}done-printer-install.txt'

  - name: Copy FSLogix files
    win_copy:
      src: '{{ item }}'
      dest: '{{ citrix.rdsh.fslogix.rulesfolder }}'
    with_fileglob:
      - "*.fxa"
      - "*.fxr"

  - name: Set DDC Reg Keys
    ansible.windows.win_regedit:
      path: HKLM\Software\Citrix
      name: VirtualDesktopAgent
      data: citrix-ctrl-01.dt.democloud

  - name: Set DDC Reg Keys
    ansible.windows.win_regedit:
      path: HKLM\Software\Wow6432Node\Citrix
      name: VirtualDesktopAgent
      data: citrix-ctrl-01.dt.democloud

  - name: Reboot
    ansible.windows.win_reboot:
    when: sw_installed.changed